# system_controller_hw.tcl - Altera Platform Designer Component Definition
# Generated by ipcraft VHDL Generator
#
# Provides component integration for Altera Quartus Platform Designer (Qsys)
# with Avalon-MM slave interface for register access.
#
# Usage: Place this file in the same directory as your VHDL files and
# add the directory to Platform Designer's IP search path.

# -----------------------------------------------------------------------------
# Package Definition
# -----------------------------------------------------------------------------
package require qsys

# -----------------------------------------------------------------------------
# Parameters
# -----------------------------------------------------------------------------
add_parameter DATA_WIDTH INTEGER 32
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME "Data Width"
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH HDL_PARAMETER true
set_parameter_property DATA_WIDTH AFFECTS_GENERATION false
set_parameter_property DATA_WIDTH AFFECTS_ELABORATION true

add_parameter ADDR_WIDTH INTEGER 32
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 32
set_parameter_property ADDR_WIDTH DISPLAY_NAME "Addr Width"
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
set_parameter_property ADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property ADDR_WIDTH AFFECTS_ELABORATION true

add_parameter FIFO_DEPTH INTEGER 1024
set_parameter_property FIFO_DEPTH DEFAULT_VALUE 1024
set_parameter_property FIFO_DEPTH DISPLAY_NAME "Fifo Depth"
set_parameter_property FIFO_DEPTH TYPE INTEGER
set_parameter_property FIFO_DEPTH UNITS None
set_parameter_property FIFO_DEPTH HDL_PARAMETER true
set_parameter_property FIFO_DEPTH AFFECTS_GENERATION false
set_parameter_property FIFO_DEPTH AFFECTS_ELABORATION true

add_parameter ENABLE_DMA BOOLEAN true
set_parameter_property ENABLE_DMA DEFAULT_VALUE true
set_parameter_property ENABLE_DMA DISPLAY_NAME "Enable Dma"
set_parameter_property ENABLE_DMA TYPE BOOLEAN
set_parameter_property ENABLE_DMA UNITS None
set_parameter_property ENABLE_DMA HDL_PARAMETER true
set_parameter_property ENABLE_DMA AFFECTS_GENERATION false
set_parameter_property ENABLE_DMA AFFECTS_ELABORATION true

# -----------------------------------------------------------------------------
# Validation Callback
# -----------------------------------------------------------------------------
proc validate {} {
# Add parameter validation here if needed
}

# -----------------------------------------------------------------------------
# Elaboration Callback
# -----------------------------------------------------------------------------
proc elaborate {} {
# -----------------------------------------------------------------------------
# Clock Interface
# -----------------------------------------------------------------------------
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1

# -----------------------------------------------------------------------------
# Reset Interface
# -----------------------------------------------------------------------------
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst reset Input 1

# -----------------------------------------------------------------------------
# Slave Interface
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Bus Interfaces (Generic)
# -----------------------------------------------------------------------------

# Interface: control_reg (ipcraft.busif.axi4_lite.1.0)
add_interface control_reg axi4lite end
set_interface_property control_reg associatedClock clk
set_interface_property control_reg associatedReset reset
set_interface_property control_reg ENABLED true
set_interface_property control_reg EXPORT_OF ""
set_interface_property control_reg PORT_NAME_MAP ""
set_interface_property control_reg CMSIS_SVD_VARIABLES ""
set_interface_property control_reg SVD_ADDRESS_GROUP ""

# Type-specific properties

# Ports
add_interface_port control_reg s_axi_ctrl_awaddr awaddr Input 32
add_interface_port control_reg s_axi_ctrl_awvalid awvalid Input 1
add_interface_port control_reg s_axi_ctrl_awready awready Output 1
add_interface_port control_reg s_axi_ctrl_awprot awprot Input 3
add_interface_port control_reg s_axi_ctrl_wdata wdata Input 32
add_interface_port control_reg s_axi_ctrl_wstrb wstrb Input 4
add_interface_port control_reg s_axi_ctrl_wvalid wvalid Input 1
add_interface_port control_reg s_axi_ctrl_wready wready Output 1
add_interface_port control_reg s_axi_ctrl_bresp bresp Output 2
add_interface_port control_reg s_axi_ctrl_bvalid bvalid Output 1
add_interface_port control_reg s_axi_ctrl_bready bready Input 1
add_interface_port control_reg s_axi_ctrl_araddr araddr Input 32
add_interface_port control_reg s_axi_ctrl_arvalid arvalid Input 1
add_interface_port control_reg s_axi_ctrl_arready arready Output 1
add_interface_port control_reg s_axi_ctrl_arprot arprot Input 3
add_interface_port control_reg s_axi_ctrl_rdata rdata Output 32
add_interface_port control_reg s_axi_ctrl_rresp rresp Output 2
add_interface_port control_reg s_axi_ctrl_rvalid rvalid Output 1
add_interface_port control_reg s_axi_ctrl_rready rready Input 1


# Interface: dma_control (ipcraft.busif.axi4_lite.1.0)
add_interface dma_control axi4lite end
set_interface_property dma_control associatedClock clk
set_interface_property dma_control associatedReset reset
set_interface_property dma_control ENABLED true
set_interface_property dma_control EXPORT_OF ""
set_interface_property dma_control PORT_NAME_MAP ""
set_interface_property dma_control CMSIS_SVD_VARIABLES ""
set_interface_property dma_control SVD_ADDRESS_GROUP ""

# Type-specific properties

# Ports
add_interface_port dma_control s_axi_dma_awaddr awaddr Input 32
add_interface_port dma_control s_axi_dma_awvalid awvalid Input 1
add_interface_port dma_control s_axi_dma_awready awready Output 1
add_interface_port dma_control s_axi_dma_awprot awprot Input 3
add_interface_port dma_control s_axi_dma_wdata wdata Input 32
add_interface_port dma_control s_axi_dma_wstrb wstrb Input 4
add_interface_port dma_control s_axi_dma_wvalid wvalid Input 1
add_interface_port dma_control s_axi_dma_wready wready Output 1
add_interface_port dma_control s_axi_dma_bresp bresp Output 2
add_interface_port dma_control s_axi_dma_bvalid bvalid Output 1
add_interface_port dma_control s_axi_dma_bready bready Input 1
add_interface_port dma_control s_axi_dma_araddr araddr Input 32
add_interface_port dma_control s_axi_dma_arvalid arvalid Input 1
add_interface_port dma_control s_axi_dma_arready arready Output 1
add_interface_port dma_control s_axi_dma_arprot arprot Input 3
add_interface_port dma_control s_axi_dma_rdata rdata Output 32
add_interface_port dma_control s_axi_dma_rresp rresp Output 2
add_interface_port dma_control s_axi_dma_rvalid rvalid Output 1
add_interface_port dma_control s_axi_dma_rready rready Input 1


# Interface: memory_port (ipcraft.busif.axi4_lite.1.0)
add_interface memory_port axi4lite start
set_interface_property memory_port associatedClock clk
set_interface_property memory_port associatedReset reset
set_interface_property memory_port ENABLED true
set_interface_property memory_port EXPORT_OF ""
set_interface_property memory_port PORT_NAME_MAP ""
set_interface_property memory_port CMSIS_SVD_VARIABLES ""
set_interface_property memory_port SVD_ADDRESS_GROUP ""

# Type-specific properties

# Ports
add_interface_port memory_port m_axi_mem_awaddr awaddr Output 32
add_interface_port memory_port m_axi_mem_awvalid awvalid Output 1
add_interface_port memory_port m_axi_mem_awready awready Input 1
add_interface_port memory_port m_axi_mem_awprot awprot Output 3
add_interface_port memory_port m_axi_mem_wdata wdata Output 32
add_interface_port memory_port m_axi_mem_wstrb wstrb Output 4
add_interface_port memory_port m_axi_mem_wvalid wvalid Output 1
add_interface_port memory_port m_axi_mem_wready wready Input 1
add_interface_port memory_port m_axi_mem_bresp bresp Input 2
add_interface_port memory_port m_axi_mem_bvalid bvalid Input 1
add_interface_port memory_port m_axi_mem_bready bready Output 1
add_interface_port memory_port m_axi_mem_araddr araddr Output 32
add_interface_port memory_port m_axi_mem_arvalid arvalid Output 1
add_interface_port memory_port m_axi_mem_arready arready Input 1
add_interface_port memory_port m_axi_mem_arprot arprot Output 3
add_interface_port memory_port m_axi_mem_rdata rdata Input 32
add_interface_port memory_port m_axi_mem_rresp rresp Input 2
add_interface_port memory_port m_axi_mem_rvalid rvalid Input 1
add_interface_port memory_port m_axi_mem_rready rready Output 1


# Interface: data_stream_in (ipcraft.busif.axi_stream.1.0)
add_interface data_stream_in axi4stream end
set_interface_property data_stream_in associatedClock clk
set_interface_property data_stream_in associatedReset reset
set_interface_property data_stream_in ENABLED true
set_interface_property data_stream_in EXPORT_OF ""
set_interface_property data_stream_in PORT_NAME_MAP ""
set_interface_property data_stream_in CMSIS_SVD_VARIABLES ""
set_interface_property data_stream_in SVD_ADDRESS_GROUP ""

# Type-specific properties

# Ports
add_interface_port data_stream_in s_axis_data_tdata tdata Input 32
add_interface_port data_stream_in s_axis_data_tvalid tvalid Input 1
add_interface_port data_stream_in s_axis_data_tready tready Output 1


# Interface: data_stream_out (ipcraft.busif.axi_stream.1.0)
add_interface data_stream_out axi4stream start
set_interface_property data_stream_out associatedClock clk
set_interface_property data_stream_out associatedReset reset
set_interface_property data_stream_out ENABLED true
set_interface_property data_stream_out EXPORT_OF ""
set_interface_property data_stream_out PORT_NAME_MAP ""
set_interface_property data_stream_out CMSIS_SVD_VARIABLES ""
set_interface_property data_stream_out SVD_ADDRESS_GROUP ""

# Type-specific properties

# Ports
add_interface_port data_stream_out m_axis_data_tdata tdata Output 32
add_interface_port data_stream_out m_axis_data_tvalid tvalid Output 1
add_interface_port data_stream_out m_axis_data_tready tready Input 1


# Interface: pcie_interface (ipcraft.busif.axi4_lite.1.0)
add_interface pcie_interface axi4lite start
set_interface_property pcie_interface associatedClock clk
set_interface_property pcie_interface associatedReset reset
set_interface_property pcie_interface ENABLED true
set_interface_property pcie_interface EXPORT_OF ""
set_interface_property pcie_interface PORT_NAME_MAP ""
set_interface_property pcie_interface CMSIS_SVD_VARIABLES ""
set_interface_property pcie_interface SVD_ADDRESS_GROUP ""

# Type-specific properties

# Ports
add_interface_port pcie_interface m_axi_pcie_awaddr awaddr Output 32
add_interface_port pcie_interface m_axi_pcie_awvalid awvalid Output 1
add_interface_port pcie_interface m_axi_pcie_awready awready Input 1
add_interface_port pcie_interface m_axi_pcie_awprot awprot Output 3
add_interface_port pcie_interface m_axi_pcie_wdata wdata Output 32
add_interface_port pcie_interface m_axi_pcie_wstrb wstrb Output 4
add_interface_port pcie_interface m_axi_pcie_wvalid wvalid Output 1
add_interface_port pcie_interface m_axi_pcie_wready wready Input 1
add_interface_port pcie_interface m_axi_pcie_bresp bresp Input 2
add_interface_port pcie_interface m_axi_pcie_bvalid bvalid Input 1
add_interface_port pcie_interface m_axi_pcie_bready bready Output 1
add_interface_port pcie_interface m_axi_pcie_araddr araddr Output 32
add_interface_port pcie_interface m_axi_pcie_arvalid arvalid Output 1
add_interface_port pcie_interface m_axi_pcie_arready arready Input 1
add_interface_port pcie_interface m_axi_pcie_arprot arprot Output 3
add_interface_port pcie_interface m_axi_pcie_rdata rdata Input 32
add_interface_port pcie_interface m_axi_pcie_rresp rresp Input 2
add_interface_port pcie_interface m_axi_pcie_rvalid rvalid Input 1
add_interface_port pcie_interface m_axi_pcie_rready rready Output 1


# Interface: usb_data_in (ipcraft.busif.axi_stream.1.0)
add_interface usb_data_in axi4stream end
set_interface_property usb_data_in associatedClock clk
set_interface_property usb_data_in associatedReset reset
set_interface_property usb_data_in ENABLED true
set_interface_property usb_data_in EXPORT_OF ""
set_interface_property usb_data_in PORT_NAME_MAP ""
set_interface_property usb_data_in CMSIS_SVD_VARIABLES ""
set_interface_property usb_data_in SVD_ADDRESS_GROUP ""

# Type-specific properties

# Ports
add_interface_port usb_data_in s_axis_usb_tdata tdata Input 32
add_interface_port usb_data_in s_axis_usb_tvalid tvalid Input 1
add_interface_port usb_data_in s_axis_usb_tready tready Output 1


# Interface: usb_data_out (ipcraft.busif.axi_stream.1.0)
add_interface usb_data_out axi4stream start
set_interface_property usb_data_out associatedClock clk
set_interface_property usb_data_out associatedReset reset
set_interface_property usb_data_out ENABLED true
set_interface_property usb_data_out EXPORT_OF ""
set_interface_property usb_data_out PORT_NAME_MAP ""
set_interface_property usb_data_out CMSIS_SVD_VARIABLES ""
set_interface_property usb_data_out SVD_ADDRESS_GROUP ""

# Type-specific properties

# Ports
add_interface_port usb_data_out m_axis_usb_tdata tdata Output 32
add_interface_port usb_data_out m_axis_usb_tvalid tvalid Output 1
add_interface_port usb_data_out m_axis_usb_tready tready Input 1



# -----------------------------------------------------------------------------
# Interrupt Interface(s)
# -----------------------------------------------------------------------------
# irq_out: interrupt sender (out)
add_interface irq_out interrupt end
set_interface_property irq_out associatedAddressablePoint ""
set_interface_property irq_out ENABLED true

add_interface_port irq_out irq_out irq Output 1

}

# -----------------------------------------------------------------------------
# Module Properties
# -----------------------------------------------------------------------------
set_module_property DESCRIPTION "A complex IP core for system-level control with many clocks, resets, and bus interfaces."
set_module_property NAME system_controller
set_module_property VERSION 1.0.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "ipcraft"
set_module_property DISPLAY_NAME "System Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property VALIDATION_CALLBACK validate
set_module_property ELABORATION_CALLBACK elaborate

# -----------------------------------------------------------------------------
# File Sets
# -----------------------------------------------------------------------------
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL system_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file system_controller_pkg.vhd VHDL PATH ../rtl/system_controller_pkg.vhd
add_fileset_file system_controller_regs.vhd VHDL PATH ../rtl/system_controller_regs.vhd
add_fileset_file system_controller_core.vhd VHDL PATH ../rtl/system_controller_core.vhd
add_fileset_file system_controller_axil.vhd VHDL PATH ../rtl/system_controller_axil.vhd
add_fileset_file system_controller.vhd VHDL PATH ../rtl/system_controller.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL system_controller
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file system_controller_pkg.vhd VHDL PATH ../rtl/system_controller_pkg.vhd
add_fileset_file system_controller_regs.vhd VHDL PATH ../rtl/system_controller_regs.vhd
add_fileset_file system_controller_core.vhd VHDL PATH ../rtl/system_controller_core.vhd
add_fileset_file system_controller_axil.vhd VHDL PATH ../rtl/system_controller_axil.vhd
add_fileset_file system_controller.vhd VHDL PATH ../rtl/system_controller.vhd TOP_LEVEL_FILE
