

--------------------------------------------------------------------------------
-- Entity: led_controller
-- Description: Top-level IP core (instantiates core + bus wrapper)
-- Generated by ipcore_lib VHDL Generator
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.led_controller_pkg.all;

entity led_controller is
  generic (
    NUM_LEDS : integer := 8;
    PWM_BITS : integer := 8;
    BLINK_COUNTER_WIDTH : integer := 24
  );
  port (
    -- Clock and reset
    i_clk : in std_logic;
    i_rst_n : in std_logic;

    -- AXIL Bus Interface
    s_axi_awaddr   : in  std_logic_vector(C_ADDR_WIDTH-1 downto 0);
    s_axi_awvalid  : in  std_logic;
    s_axi_awready  : out std_logic;
    s_axi_awprot   : in  std_logic_vector(2 downto 0);
    s_axi_wdata    : in  std_logic_vector(C_DATA_WIDTH-1 downto 0);
    s_axi_wstrb    : in  std_logic_vector((C_DATA_WIDTH/8)-1 downto 0);
    s_axi_wvalid   : in  std_logic;
    s_axi_wready   : out std_logic;
    s_axi_bresp    : out std_logic_vector(1 downto 0);
    s_axi_bvalid   : out std_logic;
    s_axi_bready   : in  std_logic;
    s_axi_araddr   : in  std_logic_vector(C_ADDR_WIDTH-1 downto 0);
    s_axi_arvalid  : in  std_logic;
    s_axi_arready  : out std_logic;
    s_axi_arprot   : in  std_logic_vector(2 downto 0);
    s_axi_rdata    : out std_logic_vector(C_DATA_WIDTH-1 downto 0);
    s_axi_rresp    : out std_logic_vector(1 downto 0);
    s_axi_rvalid   : out std_logic;
    s_axi_rready   : in  std_logic;

    -- Secondary Bus Interfaces

    -- User ports
    o_led : out std_logic_vector(NUM_LEDS-1 downto 0);
    o_led_pwm : out std_logic_vector(NUM_LEDS-1 downto 0);
    o_irq : out std_logic
    );
end entity led_controller;

architecture rtl of led_controller is

    -- Internal register signals
  signal regs_sw2hw : t_regs_sw2hw;
  signal regs_hw2sw : t_regs_hw2sw;

begin

    ----------------------------------------------------------------------------
    -- Bus Wrapper Instance
    ----------------------------------------------------------------------------
    u_axil : entity work.led_controller_axil
    port map (
      clk => i_clk,
      rst => not i_rst_n,

      s_axi_awaddr   => s_axi_awaddr,
      s_axi_awvalid  => s_axi_awvalid,
      s_axi_awready  => s_axi_awready,
      s_axi_awprot   => s_axi_awprot,
      s_axi_wdata    => s_axi_wdata,
      s_axi_wstrb    => s_axi_wstrb,
      s_axi_wvalid   => s_axi_wvalid,
      s_axi_wready   => s_axi_wready,
      s_axi_bresp    => s_axi_bresp,
      s_axi_bvalid   => s_axi_bvalid,
      s_axi_bready   => s_axi_bready,
      s_axi_araddr   => s_axi_araddr,
      s_axi_arvalid  => s_axi_arvalid,
      s_axi_arready  => s_axi_arready,
      s_axi_arprot   => s_axi_arprot,
      s_axi_rdata    => s_axi_rdata,
      s_axi_rresp    => s_axi_rresp,
      s_axi_rvalid   => s_axi_rvalid,
      s_axi_rready   => s_axi_rready,
      regs_out => regs_sw2hw,
      regs_in => regs_hw2sw
    );

    ----------------------------------------------------------------------------
    -- Core Logic Instance
    ----------------------------------------------------------------------------
    u_core : entity work.led_controller_core
    generic map (
      NUM_LEDS => NUM_LEDS,
      PWM_BITS => PWM_BITS,
      BLINK_COUNTER_WIDTH => BLINK_COUNTER_WIDTH
    )
    port map (
      clk => i_clk,
      rst => not i_rst_n,
      regs_in => regs_sw2hw,
      regs_out => regs_hw2sw,
      o_led => o_led,
      o_led_pwm => o_led_pwm,
      o_irq => o_irq
    );

end architecture rtl;
