

--------------------------------------------------------------------------------
-- Entity: led_controller_core
-- Description: Core logic module (bus-agnostic)
-- Generated by ipcore_lib VHDL Generator
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.led_controller_pkg.all;

entity led_controller_core is
  generic (
    NUM_LEDS : integer := 8;
    PWM_BITS : integer := 8;
    BLINK_COUNTER_WIDTH : integer := 24
  );
  port (
    -- Clock and reset
    clk : in std_logic;
    rst : in std_logic;

    -- Register interface (record-based)
    regs_in : in t_regs_sw2hw; -- SW-writable registers (from bus wrapper)
    regs_out : out t_regs_hw2sw; -- HW-writable registers (to bus wrapper)

    -- Secondary Bus Interfaces

    -- User ports
    o_led : out std_logic_vector(NUM_LEDS-1 downto 0);
    o_led_pwm : out std_logic_vector(NUM_LEDS-1 downto 0);
    o_irq : out std_logic
    );
end entity led_controller_core;

architecture rtl of led_controller_core is

  ----------------------------------------------------------------------------
  -- Internal Signals
  ----------------------------------------------------------------------------
  -- Add your internal signals here

begin

  ----------------------------------------------------------------------------
  -- Main Process
  ----------------------------------------------------------------------------
  p_main : process(clk)
  begin
    if rising_edge(clk) then
      if rst = '1' then
        -- Reset logic
        regs_out <= C_REGS_HW2SW_RESET;
      else
        -- Example: Access SW-writable register fields
        -- if regs_in.control.enable = '1' then
        --     -- Do something
        -- end if;

        -- Example: Update HW-writable register fields
        -- regs_out.status.busy <= '1';
        null;
      end if;
    end if;
  end process;

end architecture rtl;
