# led_controller_hw.tcl - Intel Platform Designer Component Definition
# Generated by ipcore_lib VHDL Generator
#
# Provides component integration for Intel Quartus Platform Designer (Qsys)
# with Avalon-MM slave interface for register access.
#
# Usage: Place this file in the same directory as your VHDL files and
# add the directory to Platform Designer's IP search path.

# -----------------------------------------------------------------------------
# Package Definition
# -----------------------------------------------------------------------------
package require qsys

# -----------------------------------------------------------------------------
# Validation Callback
# -----------------------------------------------------------------------------
proc validate {} {
# Add parameter validation here if needed
}

# -----------------------------------------------------------------------------
# Elaboration Callback
# -----------------------------------------------------------------------------
proc elaborate {} {
# -----------------------------------------------------------------------------
# Clock Interface
# -----------------------------------------------------------------------------
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1

# -----------------------------------------------------------------------------
# Reset Interface
# -----------------------------------------------------------------------------
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst reset Input 1

# -----------------------------------------------------------------------------
# Slave Interface
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Bus Interfaces (Generic)
# -----------------------------------------------------------------------------

# Interface: S_AXI_LITE (AXI4L)
add_interface S_AXI_LITE axi4lite end
set_interface_property S_AXI_LITE associatedClock clk
set_interface_property S_AXI_LITE associatedReset reset
set_interface_property S_AXI_LITE ENABLED true
set_interface_property S_AXI_LITE EXPORT_OF ""
set_interface_property S_AXI_LITE PORT_NAME_MAP ""
set_interface_property S_AXI_LITE CMSIS_SVD_VARIABLES ""
set_interface_property S_AXI_LITE SVD_ADDRESS_GROUP ""

# Type-specific properties
set_interface_property S_AXI_LITE readAcceptanceCapability 1
set_interface_property S_AXI_LITE writeAcceptanceCapability 1

# Ports
add_interface_port S_AXI_LITE s_axi_awaddr awaddr Input 12
add_interface_port S_AXI_LITE s_axi_awvalid awvalid Input 1
add_interface_port S_AXI_LITE s_axi_awready awready Output 1
add_interface_port S_AXI_LITE s_axi_awprot awprot Input 3
add_interface_port S_AXI_LITE s_axi_wdata wdata Input 32
add_interface_port S_AXI_LITE s_axi_wstrb wstrb Input 4
add_interface_port S_AXI_LITE s_axi_wvalid wvalid Input 1
add_interface_port S_AXI_LITE s_axi_wready wready Output 1
add_interface_port S_AXI_LITE s_axi_bresp bresp Output 2
add_interface_port S_AXI_LITE s_axi_bvalid bvalid Output 1
add_interface_port S_AXI_LITE s_axi_bready bready Input 1
add_interface_port S_AXI_LITE s_axi_araddr araddr Input 12
add_interface_port S_AXI_LITE s_axi_arvalid arvalid Input 1
add_interface_port S_AXI_LITE s_axi_arready arready Output 1
add_interface_port S_AXI_LITE s_axi_arprot arprot Input 3
add_interface_port S_AXI_LITE s_axi_rdata rdata Output 32
add_interface_port S_AXI_LITE s_axi_rresp rresp Output 2
add_interface_port S_AXI_LITE s_axi_rvalid rvalid Output 1
add_interface_port S_AXI_LITE s_axi_rready rready Input 1


# -----------------------------------------------------------------------------
# Conduit Interface (User Ports)
# -----------------------------------------------------------------------------
add_interface conduit conduit end
set_interface_property conduit associatedClock clk
set_interface_property conduit associatedReset reset
set_interface_property conduit ENABLED true
set_interface_property conduit EXPORT_OF ""
set_interface_property conduit PORT_NAME_MAP ""
set_interface_property conduit CMSIS_SVD_VARIABLES ""
set_interface_property conduit SVD_ADDRESS_GROUP ""

add_interface_port conduit o_led o_led Output NUM_LEDS
add_interface_port conduit o_led_pwm o_led_pwm Output NUM_LEDS
add_interface_port conduit o_irq o_irq Output 1
}

# -----------------------------------------------------------------------------
# Module Properties
# -----------------------------------------------------------------------------
set_module_property DESCRIPTION "A configurable LED controller IP with AXI-Lite interface supporting multiple LED outputs with individual control, PWM brightness, and blink patterns."
set_module_property NAME led_controller
set_module_property VERSION 1.0.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "test-hardware.com"
set_module_property DISPLAY_NAME "Led Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property VALIDATION_CALLBACK validate
set_module_property ELABORATION_CALLBACK elaborate

# -----------------------------------------------------------------------------
# File Sets
# -----------------------------------------------------------------------------
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL led_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file led_controller_pkg.vhd VHDL PATH ../rtl/led_controller_pkg.vhd
add_fileset_file led_controller_regs.vhd VHDL PATH ../rtl/led_controller_regs.vhd
add_fileset_file led_controller_core.vhd VHDL PATH ../rtl/led_controller_core.vhd
add_fileset_file led_controller_axil.vhd VHDL PATH ../rtl/led_controller_axil.vhd
add_fileset_file led_controller.vhd VHDL PATH ../rtl/led_controller.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL led_controller
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file led_controller_pkg.vhd VHDL PATH ../rtl/led_controller_pkg.vhd
add_fileset_file led_controller_regs.vhd VHDL PATH ../rtl/led_controller_regs.vhd
add_fileset_file led_controller_core.vhd VHDL PATH ../rtl/led_controller_core.vhd
add_fileset_file led_controller_axil.vhd VHDL PATH ../rtl/led_controller_axil.vhd
add_fileset_file led_controller.vhd VHDL PATH ../rtl/led_controller.vhd TOP_LEVEL_FILE

# -----------------------------------------------------------------------------
# Parameters
# -----------------------------------------------------------------------------
add_parameter NUM_LEDS INTEGER 8
set_parameter_property NUM_LEDS DEFAULT_VALUE 8
set_parameter_property NUM_LEDS DISPLAY_NAME "Num Leds"
set_parameter_property NUM_LEDS TYPE INTEGER
set_parameter_property NUM_LEDS UNITS None
set_parameter_property NUM_LEDS HDL_PARAMETER true
set_parameter_property NUM_LEDS AFFECTS_GENERATION false
set_parameter_property NUM_LEDS AFFECTS_ELABORATION true

add_parameter PWM_BITS INTEGER 8
set_parameter_property PWM_BITS DEFAULT_VALUE 8
set_parameter_property PWM_BITS DISPLAY_NAME "Pwm Bits"
set_parameter_property PWM_BITS TYPE INTEGER
set_parameter_property PWM_BITS UNITS None
set_parameter_property PWM_BITS HDL_PARAMETER true
set_parameter_property PWM_BITS AFFECTS_GENERATION false
set_parameter_property PWM_BITS AFFECTS_ELABORATION true

add_parameter BLINK_COUNTER_WIDTH INTEGER 24
set_parameter_property BLINK_COUNTER_WIDTH DEFAULT_VALUE 24
set_parameter_property BLINK_COUNTER_WIDTH DISPLAY_NAME "Blink Counter Width"
set_parameter_property BLINK_COUNTER_WIDTH TYPE INTEGER
set_parameter_property BLINK_COUNTER_WIDTH UNITS None
set_parameter_property BLINK_COUNTER_WIDTH HDL_PARAMETER true
set_parameter_property BLINK_COUNTER_WIDTH AFFECTS_GENERATION false
set_parameter_property BLINK_COUNTER_WIDTH AFFECTS_ELABORATION true

