--------------------------------------------------------------------------------
-- Entity: my_timer_core
-- Description: Top-level IP core (instantiates core + bus wrapper)
-- Generated by ipcore_lib VHDL Generator
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.my_timer_core_pkg.all;

entity my_timer_core is
  generic (
    NUM_CHANNELS : integer := 4;
    AXI_ADDR_WIDTH : integer := 32;
    EVENT_FIFO_DEPTH : integer := 16;
    TIMESTAMP_WIDTH : integer := 48
  );
  port (
    -- Clock and reset
    i_clk_sys : in std_logic;
    i_rst_n_sys : in std_logic;

    -- AXIL Bus Interface
    s_axi_awaddr   : in  std_logic_vector(C_ADDR_WIDTH-1 downto 0);
    s_axi_awvalid  : in  std_logic;
    s_axi_awready  : out std_logic;
    s_axi_awprot   : in  std_logic_vector(2 downto 0);
    s_axi_wdata    : in  std_logic_vector(C_DATA_WIDTH-1 downto 0);
    s_axi_wstrb    : in  std_logic_vector((C_DATA_WIDTH/8)-1 downto 0);
    s_axi_wvalid   : in  std_logic;
    s_axi_wready   : out std_logic;
    s_axi_bresp    : out std_logic_vector(1 downto 0);
    s_axi_bvalid   : out std_logic;
    s_axi_bready   : in  std_logic;
    s_axi_araddr   : in  std_logic_vector(C_ADDR_WIDTH-1 downto 0);
    s_axi_arvalid  : in  std_logic;
    s_axi_arready  : out std_logic;
    s_axi_arprot   : in  std_logic_vector(2 downto 0);
    s_axi_rdata    : out std_logic_vector(C_DATA_WIDTH-1 downto 0);
    s_axi_rresp    : out std_logic_vector(1 downto 0);
    s_axi_rvalid   : out std_logic;
    s_axi_rready   : in  std_logic;

    -- Secondary Bus Interfaces
    m_axis_ch0_evt_tdata : out std_logic_vector(63 downto 0);
    m_axis_ch0_evt_tvalid : out std_logic;
    m_axis_ch0_evt_tready : in  std_logic;
    m_axis_ch0_evt_tlast : out std_logic;
    m_axis_ch0_evt_tuser : out std_logic_vector(3 downto 0);
    m_axis_ch1_evt_tdata : out std_logic_vector(63 downto 0);
    m_axis_ch1_evt_tvalid : out std_logic;
    m_axis_ch1_evt_tready : in  std_logic;
    m_axis_ch1_evt_tlast : out std_logic;
    m_axis_ch1_evt_tuser : out std_logic_vector(3 downto 0);
    m_axis_ch2_evt_tdata : out std_logic_vector(63 downto 0);
    m_axis_ch2_evt_tvalid : out std_logic;
    m_axis_ch2_evt_tready : in  std_logic;
    m_axis_ch2_evt_tlast : out std_logic;
    m_axis_ch2_evt_tuser : out std_logic_vector(3 downto 0);
    m_axis_ch3_evt_tdata : out std_logic_vector(63 downto 0);
    m_axis_ch3_evt_tvalid : out std_logic;
    m_axis_ch3_evt_tready : in  std_logic;
    m_axis_ch3_evt_tlast : out std_logic;
    m_axis_ch3_evt_tuser : out std_logic_vector(3 downto 0);

    -- User ports
    o_global_irq : out std_logic
    );
end entity my_timer_core;

architecture rtl of my_timer_core is

    -- Internal register signals
  signal regs_sw2hw : t_regs_sw2hw;
  signal regs_hw2sw : t_regs_hw2sw;

begin

    ----------------------------------------------------------------------------
    -- Bus Wrapper Instance
    ----------------------------------------------------------------------------
    u_axil : entity work.my_timer_core_axil
    port map (
      clk => i_clk_sys,
      rst => not i_rst_n_sys,

      s_axi_awaddr   => s_axi_awaddr,
      s_axi_awvalid  => s_axi_awvalid,
      s_axi_awready  => s_axi_awready,
      s_axi_awprot   => s_axi_awprot,
      s_axi_wdata    => s_axi_wdata,
      s_axi_wstrb    => s_axi_wstrb,
      s_axi_wvalid   => s_axi_wvalid,
      s_axi_wready   => s_axi_wready,
      s_axi_bresp    => s_axi_bresp,
      s_axi_bvalid   => s_axi_bvalid,
      s_axi_bready   => s_axi_bready,
      s_axi_araddr   => s_axi_araddr,
      s_axi_arvalid  => s_axi_arvalid,
      s_axi_arready  => s_axi_arready,
      s_axi_arprot   => s_axi_arprot,
      s_axi_rdata    => s_axi_rdata,
      s_axi_rresp    => s_axi_rresp,
      s_axi_rvalid   => s_axi_rvalid,
      s_axi_rready   => s_axi_rready,
      regs_out => regs_sw2hw,
      regs_in => regs_hw2sw
    );

    ----------------------------------------------------------------------------
    -- Core Logic Instance
    ----------------------------------------------------------------------------
    u_core : entity work.my_timer_core_core
    generic map (
      NUM_CHANNELS => NUM_CHANNELS,
      AXI_ADDR_WIDTH => AXI_ADDR_WIDTH,
      EVENT_FIFO_DEPTH => EVENT_FIFO_DEPTH,
      TIMESTAMP_WIDTH => TIMESTAMP_WIDTH
    )
    port map (
      clk => i_clk_sys,
      rst => not i_rst_n_sys,
      regs_in => regs_sw2hw,
      regs_out => regs_hw2sw,
      m_axis_ch0_evt_tdata => m_axis_ch0_evt_tdata,
      m_axis_ch0_evt_tvalid => m_axis_ch0_evt_tvalid,
      m_axis_ch0_evt_tready => m_axis_ch0_evt_tready,
      m_axis_ch0_evt_tlast => m_axis_ch0_evt_tlast,
      m_axis_ch0_evt_tuser => m_axis_ch0_evt_tuser,
      m_axis_ch1_evt_tdata => m_axis_ch1_evt_tdata,
      m_axis_ch1_evt_tvalid => m_axis_ch1_evt_tvalid,
      m_axis_ch1_evt_tready => m_axis_ch1_evt_tready,
      m_axis_ch1_evt_tlast => m_axis_ch1_evt_tlast,
      m_axis_ch1_evt_tuser => m_axis_ch1_evt_tuser,
      m_axis_ch2_evt_tdata => m_axis_ch2_evt_tdata,
      m_axis_ch2_evt_tvalid => m_axis_ch2_evt_tvalid,
      m_axis_ch2_evt_tready => m_axis_ch2_evt_tready,
      m_axis_ch2_evt_tlast => m_axis_ch2_evt_tlast,
      m_axis_ch2_evt_tuser => m_axis_ch2_evt_tuser,
      m_axis_ch3_evt_tdata => m_axis_ch3_evt_tdata,
      m_axis_ch3_evt_tvalid => m_axis_ch3_evt_tvalid,
      m_axis_ch3_evt_tready => m_axis_ch3_evt_tready,
      m_axis_ch3_evt_tlast => m_axis_ch3_evt_tlast,
      m_axis_ch3_evt_tuser => m_axis_ch3_evt_tuser,
      o_global_irq => o_global_irq
    );

end architecture rtl;