

--------------------------------------------------------------------------------
-- Entity: system_controller
-- Description: A complex IP core for system-level control with many clocks, resets, and bus interfaces.
-- Generated by ipcraft VHDL Generator
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.system_controller_pkg.all;

entity system_controller is
  generic (
    DATA_WIDTH : integer := 32;
    ADDR_WIDTH : integer := 32;
    FIFO_DEPTH : integer := 1024;
    ENABLE_DMA : boolean := true
  );
  port (
    -- Clock and reset
    CLK_SYS : in std_logic;
    RST_SYS : in std_logic;


    -- control_reg (SLAVE)
    s_axi_ctrl_awaddr : in  std_logic_vector(C_ADDR_WIDTH-1 downto 0);
    s_axi_ctrl_awvalid : in  std_logic;
    s_axi_ctrl_awready : out std_logic;
    s_axi_ctrl_awprot : in  std_logic_vector(2 downto 0);
    s_axi_ctrl_wdata : in  std_logic_vector(C_DATA_WIDTH-1 downto 0);
    s_axi_ctrl_wstrb : in  std_logic_vector((C_DATA_WIDTH/8)-1 downto 0);
    s_axi_ctrl_wvalid : in  std_logic;
    s_axi_ctrl_wready : out std_logic;
    s_axi_ctrl_bresp : out std_logic_vector(1 downto 0);
    s_axi_ctrl_bvalid : out std_logic;
    s_axi_ctrl_bready : in  std_logic;
    s_axi_ctrl_araddr : in  std_logic_vector(C_ADDR_WIDTH-1 downto 0);
    s_axi_ctrl_arvalid : in  std_logic;
    s_axi_ctrl_arready : out std_logic;
    s_axi_ctrl_arprot : in  std_logic_vector(2 downto 0);
    s_axi_ctrl_rdata : out std_logic_vector(C_DATA_WIDTH-1 downto 0);
    s_axi_ctrl_rresp : out std_logic_vector(1 downto 0);
    s_axi_ctrl_rvalid : out std_logic;
    s_axi_ctrl_rready : in  std_logic;

    -- dma_control (SLAVE)
    s_axi_dma_awaddr : in  std_logic_vector(C_ADDR_WIDTH-1 downto 0);
    s_axi_dma_awvalid : in  std_logic;
    s_axi_dma_awready : out std_logic;
    s_axi_dma_awprot : in  std_logic_vector(2 downto 0);
    s_axi_dma_wdata : in  std_logic_vector(C_DATA_WIDTH-1 downto 0);
    s_axi_dma_wstrb : in  std_logic_vector((C_DATA_WIDTH/8)-1 downto 0);
    s_axi_dma_wvalid : in  std_logic;
    s_axi_dma_wready : out std_logic;
    s_axi_dma_bresp : out std_logic_vector(1 downto 0);
    s_axi_dma_bvalid : out std_logic;
    s_axi_dma_bready : in  std_logic;
    s_axi_dma_araddr : in  std_logic_vector(C_ADDR_WIDTH-1 downto 0);
    s_axi_dma_arvalid : in  std_logic;
    s_axi_dma_arready : out std_logic;
    s_axi_dma_arprot : in  std_logic_vector(2 downto 0);
    s_axi_dma_rdata : out std_logic_vector(C_DATA_WIDTH-1 downto 0);
    s_axi_dma_rresp : out std_logic_vector(1 downto 0);
    s_axi_dma_rvalid : out std_logic;
    s_axi_dma_rready : in  std_logic;

    -- memory_port (MASTER)
    m_axi_mem_awaddr : out std_logic_vector(C_ADDR_WIDTH-1 downto 0);
    m_axi_mem_awvalid : out std_logic;
    m_axi_mem_awready : in  std_logic;
    m_axi_mem_awprot : out std_logic_vector(2 downto 0);
    m_axi_mem_wdata : out std_logic_vector(C_DATA_WIDTH-1 downto 0);
    m_axi_mem_wstrb : out std_logic_vector((C_DATA_WIDTH/8)-1 downto 0);
    m_axi_mem_wvalid : out std_logic;
    m_axi_mem_wready : in  std_logic;
    m_axi_mem_bresp : in  std_logic_vector(1 downto 0);
    m_axi_mem_bvalid : in  std_logic;
    m_axi_mem_bready : out std_logic;
    m_axi_mem_araddr : out std_logic_vector(C_ADDR_WIDTH-1 downto 0);
    m_axi_mem_arvalid : out std_logic;
    m_axi_mem_arready : in  std_logic;
    m_axi_mem_arprot : out std_logic_vector(2 downto 0);
    m_axi_mem_rdata : in  std_logic_vector(C_DATA_WIDTH-1 downto 0);
    m_axi_mem_rresp : in  std_logic_vector(1 downto 0);
    m_axi_mem_rvalid : in  std_logic;
    m_axi_mem_rready : out std_logic;

    -- data_stream_in (SLAVE)
    s_axis_data_tdata : in  std_logic_vector(31 downto 0);
    s_axis_data_tvalid : in  std_logic;
    s_axis_data_tready : out std_logic;

    -- data_stream_out (MASTER)
    m_axis_data_tdata : out std_logic_vector(31 downto 0);
    m_axis_data_tvalid : out std_logic;
    m_axis_data_tready : in  std_logic;

    -- pcie_interface (MASTER)
    m_axi_pcie_awaddr : out std_logic_vector(C_ADDR_WIDTH-1 downto 0);
    m_axi_pcie_awvalid : out std_logic;
    m_axi_pcie_awready : in  std_logic;
    m_axi_pcie_awprot : out std_logic_vector(2 downto 0);
    m_axi_pcie_wdata : out std_logic_vector(C_DATA_WIDTH-1 downto 0);
    m_axi_pcie_wstrb : out std_logic_vector((C_DATA_WIDTH/8)-1 downto 0);
    m_axi_pcie_wvalid : out std_logic;
    m_axi_pcie_wready : in  std_logic;
    m_axi_pcie_bresp : in  std_logic_vector(1 downto 0);
    m_axi_pcie_bvalid : in  std_logic;
    m_axi_pcie_bready : out std_logic;
    m_axi_pcie_araddr : out std_logic_vector(C_ADDR_WIDTH-1 downto 0);
    m_axi_pcie_arvalid : out std_logic;
    m_axi_pcie_arready : in  std_logic;
    m_axi_pcie_arprot : out std_logic_vector(2 downto 0);
    m_axi_pcie_rdata : in  std_logic_vector(C_DATA_WIDTH-1 downto 0);
    m_axi_pcie_rresp : in  std_logic_vector(1 downto 0);
    m_axi_pcie_rvalid : in  std_logic;
    m_axi_pcie_rready : out std_logic;

    -- usb_data_in (SLAVE)
    s_axis_usb_tdata : in  std_logic_vector(31 downto 0);
    s_axis_usb_tvalid : in  std_logic;
    s_axis_usb_tready : out std_logic;

    -- usb_data_out (MASTER)
    m_axis_usb_tdata : out std_logic_vector(31 downto 0);
    m_axis_usb_tvalid : out std_logic;
    m_axis_usb_tready : in  std_logic
    );
end entity system_controller;

architecture rtl of system_controller is

    -- Internal register signals
  signal regs_sw2hw : t_regs_sw2hw;
  signal regs_hw2sw : t_regs_hw2sw;

begin

    ----------------------------------------------------------------------------
    -- Bus Wrapper Instance
    ----------------------------------------------------------------------------
    u_axil : entity work.system_controller_axil
    port map (
      clk => CLK_SYS,
      rst => not RST_SYS,

      s_axi_ctrl_awaddr => s_axi_ctrl_awaddr,
      s_axi_ctrl_awvalid => s_axi_ctrl_awvalid,
      s_axi_ctrl_awready => s_axi_ctrl_awready,
      s_axi_ctrl_awprot => s_axi_ctrl_awprot,
      s_axi_ctrl_wdata => s_axi_ctrl_wdata,
      s_axi_ctrl_wstrb => s_axi_ctrl_wstrb,
      s_axi_ctrl_wvalid => s_axi_ctrl_wvalid,
      s_axi_ctrl_wready => s_axi_ctrl_wready,
      s_axi_ctrl_bresp => s_axi_ctrl_bresp,
      s_axi_ctrl_bvalid => s_axi_ctrl_bvalid,
      s_axi_ctrl_bready => s_axi_ctrl_bready,
      s_axi_ctrl_araddr => s_axi_ctrl_araddr,
      s_axi_ctrl_arvalid => s_axi_ctrl_arvalid,
      s_axi_ctrl_arready => s_axi_ctrl_arready,
      s_axi_ctrl_arprot => s_axi_ctrl_arprot,
      s_axi_ctrl_rdata => s_axi_ctrl_rdata,
      s_axi_ctrl_rresp => s_axi_ctrl_rresp,
      s_axi_ctrl_rvalid => s_axi_ctrl_rvalid,
      s_axi_ctrl_rready => s_axi_ctrl_rready,
      regs_out => regs_sw2hw,
      regs_in => regs_hw2sw
    );

    ----------------------------------------------------------------------------
    -- Core Logic Instance
    ----------------------------------------------------------------------------
    u_core : entity work.system_controller_core
    generic map (
      DATA_WIDTH => DATA_WIDTH,
      ADDR_WIDTH => ADDR_WIDTH,
      FIFO_DEPTH => FIFO_DEPTH,
      ENABLE_DMA => ENABLE_DMA
    )
    port map (
      clk => CLK_SYS,
      rst => not RST_SYS,
      regs_in => regs_sw2hw,
      regs_out => regs_hw2sw,
      s_axi_dma_awaddr => s_axi_dma_awaddr,
      s_axi_dma_awvalid => s_axi_dma_awvalid,
      s_axi_dma_awready => s_axi_dma_awready,
      s_axi_dma_awprot => s_axi_dma_awprot,
      s_axi_dma_wdata => s_axi_dma_wdata,
      s_axi_dma_wstrb => s_axi_dma_wstrb,
      s_axi_dma_wvalid => s_axi_dma_wvalid,
      s_axi_dma_wready => s_axi_dma_wready,
      s_axi_dma_bresp => s_axi_dma_bresp,
      s_axi_dma_bvalid => s_axi_dma_bvalid,
      s_axi_dma_bready => s_axi_dma_bready,
      s_axi_dma_araddr => s_axi_dma_araddr,
      s_axi_dma_arvalid => s_axi_dma_arvalid,
      s_axi_dma_arready => s_axi_dma_arready,
      s_axi_dma_arprot => s_axi_dma_arprot,
      s_axi_dma_rdata => s_axi_dma_rdata,
      s_axi_dma_rresp => s_axi_dma_rresp,
      s_axi_dma_rvalid => s_axi_dma_rvalid,
      s_axi_dma_rready => s_axi_dma_rready,
      m_axi_mem_awaddr => m_axi_mem_awaddr,
      m_axi_mem_awvalid => m_axi_mem_awvalid,
      m_axi_mem_awready => m_axi_mem_awready,
      m_axi_mem_awprot => m_axi_mem_awprot,
      m_axi_mem_wdata => m_axi_mem_wdata,
      m_axi_mem_wstrb => m_axi_mem_wstrb,
      m_axi_mem_wvalid => m_axi_mem_wvalid,
      m_axi_mem_wready => m_axi_mem_wready,
      m_axi_mem_bresp => m_axi_mem_bresp,
      m_axi_mem_bvalid => m_axi_mem_bvalid,
      m_axi_mem_bready => m_axi_mem_bready,
      m_axi_mem_araddr => m_axi_mem_araddr,
      m_axi_mem_arvalid => m_axi_mem_arvalid,
      m_axi_mem_arready => m_axi_mem_arready,
      m_axi_mem_arprot => m_axi_mem_arprot,
      m_axi_mem_rdata => m_axi_mem_rdata,
      m_axi_mem_rresp => m_axi_mem_rresp,
      m_axi_mem_rvalid => m_axi_mem_rvalid,
      m_axi_mem_rready => m_axi_mem_rready,
      s_axis_data_tdata => s_axis_data_tdata,
      s_axis_data_tvalid => s_axis_data_tvalid,
      s_axis_data_tready => s_axis_data_tready,
      m_axis_data_tdata => m_axis_data_tdata,
      m_axis_data_tvalid => m_axis_data_tvalid,
      m_axis_data_tready => m_axis_data_tready,
      m_axi_pcie_awaddr => m_axi_pcie_awaddr,
      m_axi_pcie_awvalid => m_axi_pcie_awvalid,
      m_axi_pcie_awready => m_axi_pcie_awready,
      m_axi_pcie_awprot => m_axi_pcie_awprot,
      m_axi_pcie_wdata => m_axi_pcie_wdata,
      m_axi_pcie_wstrb => m_axi_pcie_wstrb,
      m_axi_pcie_wvalid => m_axi_pcie_wvalid,
      m_axi_pcie_wready => m_axi_pcie_wready,
      m_axi_pcie_bresp => m_axi_pcie_bresp,
      m_axi_pcie_bvalid => m_axi_pcie_bvalid,
      m_axi_pcie_bready => m_axi_pcie_bready,
      m_axi_pcie_araddr => m_axi_pcie_araddr,
      m_axi_pcie_arvalid => m_axi_pcie_arvalid,
      m_axi_pcie_arready => m_axi_pcie_arready,
      m_axi_pcie_arprot => m_axi_pcie_arprot,
      m_axi_pcie_rdata => m_axi_pcie_rdata,
      m_axi_pcie_rresp => m_axi_pcie_rresp,
      m_axi_pcie_rvalid => m_axi_pcie_rvalid,
      m_axi_pcie_rready => m_axi_pcie_rready,
      s_axis_usb_tdata => s_axis_usb_tdata,
      s_axis_usb_tvalid => s_axis_usb_tvalid,
      s_axis_usb_tready => s_axis_usb_tready,
      m_axis_usb_tdata => m_axis_usb_tdata,
      m_axis_usb_tvalid => m_axis_usb_tvalid,
      m_axis_usb_tready => m_axis_usb_tready
    );

end architecture rtl;
