

--------------------------------------------------------------------------------
-- Entity: system_controller_core
-- Description: Core logic module (bus-agnostic)
-- Generated by ipcraft VHDL Generator
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.system_controller_pkg.all;

entity system_controller_core is
  generic (
    DATA_WIDTH : integer := 32;
    ADDR_WIDTH : integer := 32;
    FIFO_DEPTH : integer := 1024;
    ENABLE_DMA : boolean := true
  );
  port (
    -- Clock and reset
    clk : in std_logic;
    rst : in std_logic;

    -- Register interface (record-based)
    regs_in : in t_regs_sw2hw; -- SW-writable registers (from bus wrapper)
    regs_out : out t_regs_hw2sw; -- HW-writable registers (to bus wrapper)

    -- Secondary Bus Interfaces
    s_axi_dma_awaddr : in  std_logic_vector(C_ADDR_WIDTH-1 downto 0);
    s_axi_dma_awvalid : in  std_logic;
    s_axi_dma_awready : out std_logic;
    s_axi_dma_awprot : in  std_logic_vector(2 downto 0);
    s_axi_dma_wdata : in  std_logic_vector(C_DATA_WIDTH-1 downto 0);
    s_axi_dma_wstrb : in  std_logic_vector((C_DATA_WIDTH/8)-1 downto 0);
    s_axi_dma_wvalid : in  std_logic;
    s_axi_dma_wready : out std_logic;
    s_axi_dma_bresp : out std_logic_vector(1 downto 0);
    s_axi_dma_bvalid : out std_logic;
    s_axi_dma_bready : in  std_logic;
    s_axi_dma_araddr : in  std_logic_vector(C_ADDR_WIDTH-1 downto 0);
    s_axi_dma_arvalid : in  std_logic;
    s_axi_dma_arready : out std_logic;
    s_axi_dma_arprot : in  std_logic_vector(2 downto 0);
    s_axi_dma_rdata : out std_logic_vector(C_DATA_WIDTH-1 downto 0);
    s_axi_dma_rresp : out std_logic_vector(1 downto 0);
    s_axi_dma_rvalid : out std_logic;
    s_axi_dma_rready : in  std_logic;
    m_axi_mem_awaddr : out std_logic_vector(C_ADDR_WIDTH-1 downto 0);
    m_axi_mem_awvalid : out std_logic;
    m_axi_mem_awready : in  std_logic;
    m_axi_mem_awprot : out std_logic_vector(2 downto 0);
    m_axi_mem_wdata : out std_logic_vector(C_DATA_WIDTH-1 downto 0);
    m_axi_mem_wstrb : out std_logic_vector((C_DATA_WIDTH/8)-1 downto 0);
    m_axi_mem_wvalid : out std_logic;
    m_axi_mem_wready : in  std_logic;
    m_axi_mem_bresp : in  std_logic_vector(1 downto 0);
    m_axi_mem_bvalid : in  std_logic;
    m_axi_mem_bready : out std_logic;
    m_axi_mem_araddr : out std_logic_vector(C_ADDR_WIDTH-1 downto 0);
    m_axi_mem_arvalid : out std_logic;
    m_axi_mem_arready : in  std_logic;
    m_axi_mem_arprot : out std_logic_vector(2 downto 0);
    m_axi_mem_rdata : in  std_logic_vector(C_DATA_WIDTH-1 downto 0);
    m_axi_mem_rresp : in  std_logic_vector(1 downto 0);
    m_axi_mem_rvalid : in  std_logic;
    m_axi_mem_rready : out std_logic;
    s_axis_data_tdata : in  std_logic_vector(31 downto 0);
    s_axis_data_tvalid : in  std_logic;
    s_axis_data_tready : out std_logic;
    m_axis_data_tdata : out std_logic_vector(31 downto 0);
    m_axis_data_tvalid : out std_logic;
    m_axis_data_tready : in  std_logic;
    m_axi_pcie_awaddr : out std_logic_vector(C_ADDR_WIDTH-1 downto 0);
    m_axi_pcie_awvalid : out std_logic;
    m_axi_pcie_awready : in  std_logic;
    m_axi_pcie_awprot : out std_logic_vector(2 downto 0);
    m_axi_pcie_wdata : out std_logic_vector(C_DATA_WIDTH-1 downto 0);
    m_axi_pcie_wstrb : out std_logic_vector((C_DATA_WIDTH/8)-1 downto 0);
    m_axi_pcie_wvalid : out std_logic;
    m_axi_pcie_wready : in  std_logic;
    m_axi_pcie_bresp : in  std_logic_vector(1 downto 0);
    m_axi_pcie_bvalid : in  std_logic;
    m_axi_pcie_bready : out std_logic;
    m_axi_pcie_araddr : out std_logic_vector(C_ADDR_WIDTH-1 downto 0);
    m_axi_pcie_arvalid : out std_logic;
    m_axi_pcie_arready : in  std_logic;
    m_axi_pcie_arprot : out std_logic_vector(2 downto 0);
    m_axi_pcie_rdata : in  std_logic_vector(C_DATA_WIDTH-1 downto 0);
    m_axi_pcie_rresp : in  std_logic_vector(1 downto 0);
    m_axi_pcie_rvalid : in  std_logic;
    m_axi_pcie_rready : out std_logic;
    s_axis_usb_tdata : in  std_logic_vector(31 downto 0);
    s_axis_usb_tvalid : in  std_logic;
    s_axis_usb_tready : out std_logic;
    m_axis_usb_tdata : out std_logic_vector(31 downto 0);
    m_axis_usb_tvalid : out std_logic;
    m_axis_usb_tready : in  std_logic
    );
end entity system_controller_core;

architecture rtl of system_controller_core is

  ----------------------------------------------------------------------------
  -- Internal Signals
  ----------------------------------------------------------------------------
  -- Add your internal signals here

begin

  ----------------------------------------------------------------------------
  -- Main Process
  ----------------------------------------------------------------------------
  p_main : process(clk)
  begin
    if rising_edge(clk) then
      if rst = '1' then
        -- Reset logic
        regs_out <= C_REGS_HW2SW_RESET;
      else
        -- Example: Access SW-writable register fields
        -- if regs_in.control.enable = '1' then
        --     -- Do something
        -- end if;

        -- Example: Update HW-writable register fields
        -- regs_out.status.busy <= '1';
        null;
      end if;
    end if;
  end process;

end architecture rtl;
