

--------------------------------------------------------------------------------
-- Package: system_controller_pkg
-- Generated by ipcraft VHDL Generator
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package system_controller_pkg is

  ----------------------------------------------------------------------------
  -- Constants
  ----------------------------------------------------------------------------
  constant C_DATA_WIDTH : natural := 32;
  constant C_ADDR_WIDTH : natural := 8;
  constant C_REG_WIDTH  : natural := 4;  -- Bytes per register

  ----------------------------------------------------------------------------
  -- Register Enumeration (Order defines address)
  ----------------------------------------------------------------------------
  type t_reg_id is (
  );

  -- Calculate register address from enumeration
  function reg_addr(reg : t_reg_id) return natural;

  ----------------------------------------------------------------------------
  -- Register Record Types
  ----------------------------------------------------------------------------

  ----------------------------------------------------------------------------
  -- Aggregate Register Records (for clean port interface)
  ----------------------------------------------------------------------------

  -- SW -> HW: Registers written by software, read by hardware
  type t_regs_sw2hw is record
  end record;

  constant C_REGS_SW2HW_RESET : t_regs_sw2hw := (
  );

  -- HW -> SW: Registers written by hardware, read by software
  type t_regs_hw2sw is record
  end record;

  constant C_REGS_HW2SW_RESET : t_regs_hw2sw := (
  );

end package system_controller_pkg;


package body system_controller_pkg is

  ----------------------------------------------------------------------------
  -- Register Address Function
  ----------------------------------------------------------------------------
  function reg_addr(reg : t_reg_id) return natural is
  begin
    return t_reg_id'pos(reg) * C_REG_WIDTH;
  end function;

  ----------------------------------------------------------------------------
  -- Conversion Functions
  ----------------------------------------------------------------------------

end package body system_controller_pkg;
